### ISSUE TITLE
Blueprints on MacOS

### ISSUE THREAD

**Issue by venaturum** [canonical/multipass-blueprints#41]
I'm hoping to boot a VM based on Rocky.

Is there a way to get this to work on MacOS?

Or should I launch a multipass instance, then install multipass inside that, and then follow the linux instructions to end up with a Rocky VM running on an Ubuntu VM running on MacOS?

**Comment by georgeliao** [comment]
Hi @venaturum , thanks for the reporting this. I do not think nested multipass will work, due to the limitation of the nested virtualization. However, maybe you can try to use the docker blueprint of multipass, (`multipass launch docker -n vm1`) which creates a container on the top of a multipass virtual machine instance. Then use docker to create rockylinux.

**Comment by venaturum** [comment]
Thanks @georgeliao, I'll give it a try
